language: php

os:
    - linux

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_install:
    - if [ php -v | grep -q 'Xdebug' ]; then phpenv config-rm xdebug.ini; fi

install:
    - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

jobs:
    fast_finish: true
    allow_failures:
        -   php: nightly
    include:
        # Unit Tests
        -   php: 7.1
            env:
                - COMPOSER_FLAGS="--prefer-lowest"
        -   php: 7.2
        -   php: 7.3
        -   php: 7.4
        -   php: nightly
            env:
                - COMPOSER_FLAGS="--ignore-platform-reqs"

        # Metrics and Quality
        -   name: Code Coverage
            php: 7.4
            before_script:
                - mkdir -p build/logs
            script:
                - phpdbg -qrr ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
            after_script:
                - travis_retry wget https://scrutinizer-ci.com/ocular.phar
                - travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

        -   name: Psalm
            php: 7.4
            script:
                - ./vendor/bin/psalm

        -   name: PHP Code Style Sniffer
            php: 7.4
            script:
                - ./vendor/bin/phpcs --standard=php_cs.xml ./src ./tests

        -   name: PHP Coding Standards Fixer
            php: 7.4
            before_script:
                - travis_retry wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
                - chmod a+x php-cs-fixer
            script:
                - ./php-cs-fixer fix --dry-run --stop-on-violation --using-cache=no
